#ifndef INTERLEAVED_ADDRESSING_WITH_DIVERGENT_BRANCHING
#define INTERLEAVED_ADDRESSING_WITH_DIVERGENT_BRANCHING

__global__ void reduce_using_1_interleaved_addressing_with_divergent_branching(int *input_data, int *output_data, unsigned int n);

#endif // INTERLEAVED_ADDRESSING_WITH_DIVERGENT_BRANCHING
